### PR TITLE
fix(#152): Added support for v4 simulation configuration

### LINKED ISSUE #152: Hoverfly-java doesn't support v4 simulation configuration
In the latest version of the simulation configuration (v4), there is a support for new parameters that are using a state:
https://docs.hoverfly.io/en/v0.15.0/pages/keyconcepts/state/state.html

* request
  * requiresState

* response
  * transitionsState
  * removesState

but since the hoverfly-java doesn't support this config file version, it is not possible to use it in java tests.

### PR DESCRIPTION
**Pull request by MatousJobanek**
as part of this new simulation configuration version, there is a support for new parameters that are using a state:

* request
  * requiresState

* response
  * transitionsState
  * removesState

fixes #152

### CODE REVIEW

File: src/test/java/io/specto/hoverfly/ruletest/HoverflyDslWithStateTest.java [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+            .willReturn(success().removesState("hasBeenAlreadyCreated"))
+
+            .get("/remove-without-required-state")
+            .willReturn(success().removesState("hasBeenAlreadyCreated"))
+    )).printSimulationData();
+
+    private final RestTemplate restTemplate = new RestTemplate();
+
+    @Before
+    public void removeState(){
```
Comment (tommysitu) [inline src/test/java/io/specto/hoverfly/ruletest/HoverflyDslWithStateTest.java]: Is this for resetting all the states before each test? It'd be better to add a `resetStates` method to `HoverflyRule` by calling this API: http://hoverfly.readthedocs.io/en/latest/pages/reference/api/api.html#delete-api-v2-state

File: src/test/java/io/specto/hoverfly/ruletest/HoverflyDslWithStateTest.java [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.assertj.core.api.Assertions.assertThatExceptionOfType;
+
+public class HoverflyDslWithStateTest {
+
+    @ClassRule
+    public static HoverflyRule hoverflyRule = HoverflyRule.inSimulationMode(dsl(
+        service("www.service-with-state.com")
+            .get("/api/bookings/create")
+            .willReturn(success().transitionsState("hasBeenAlreadyCreated", "true"))
```
Comment (tommysitu) [inline src/test/java/io/specto/hoverfly/ruletest/HoverflyDslWithStateTest.java]: I don't know why we called this `transitionsState` in Hoverfly, but we don't need to make it 100% matching the JSON field name in the simulation file. At the end of the day, we want to make the JAVA DSL a bit easier to write and understand. 

So perhaps, the DSL with state should read like this:
```
service("www.service-with-state.com")
            .delete("/api/bookings/1")
            .withState("Booking", "Reserved")
            .withState("Voucher Redeemd", "true")
            .willReturn(success().andSetState("Booking", "Deleted").andRemoveState("Voucher Reddemed"))
```
`withState` instead of `requiresState`
`andSetState` instead of `transitionsState`
`andRemoveState` instead of `removeState` (because it is an action rather than as part of the response body) 

What do you think?

**Comment by tommysitu** [comment]
Apart from two suggestions, the PR looks good! We are long overdue to add v4 support to Hoverfly-Java, thank you for fixing it!

File: src/test/java/io/specto/hoverfly/ruletest/HoverflyDslWithStateTest.java (hunk 2 above)
Comment (MatousJobanek) [reply src/test/java/io/specto/hoverfly/ruletest/HoverflyDslWithStateTest.java]: Yes, this is much better.
I named it in that way since I wanted to keep the same format as it had been already used for the other parameters.

**Comment by tommysitu** [comment]
It is gonna be v0.10.0, as it is using new schema and support stateful simulation. I will try to do a release early next week.

**Comment by MatousJobanek** [comment]
> It is gonna be v0.10.0, as it is using new schema and support stateful simulation. I will try to do a release early next week.

Cool, thanks a lot! 👍

**Comment by MatousJobanek** [comment]
Hi @tommysitu any update on the release? It would be good to have the fix released so we can incorporate it into our test suite.

**Comment by tommysitu** [comment]
Hi,

I was away on a trip. I am doing a release tomorrow.

Tommy

On 19 Feb 2018, at 4:32 pm, Matous Jobanek <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @tommysitu<https://github.com/tommysitu> any update on the release? It would be good to have the fix released so we can incorporate it into our test suite.

**Comment by tommysitu** [comment]
V0.10.0 is released. Thank you for your contributions! @MatousJobanek
